version: '3'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DATABASE_URL='mysql://root:2002@localhost:3306/key-service'
      - JWT_SECRET='zxqf7p7D^e5vY^Gz!%p9Rt^Xh$MqATF8'
    volumes:
      - ./auth-service:/app
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {
    driver: local
  }
